故障連絡票:
  故障番号: {故障番号}
  発生日時: {発生日時}
  故障概要: {故障の概要}
  詳細情報:
    内容: |
      {故障詳細本文}
  影響範囲: {影響範囲}
  連絡先:
    担当者: {担当者名}
    連絡先: {連絡先メールまたは電話}
  先行資材: {資材名やID}
  後続資材: {資材名やID}
  対応期限: {YYYY-MM-DD}
  備考・注意事項: |
      {必要に応じて追加情報や注意点}
